server:
  port: 9080

spring:
  application:
    name: transaction-service

  config:
    import: 'optional:configserver:'

  datasource:
    url: jdbc:mysql://localhost:3306/transaction_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: suBbu@2004

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

  cloud:
    discovery:
      enabled: false

# Feign Client Configuration
account-service:
  url: http://localhost:9081

branch-service:
  url: http://localhost:9082

loan-service:
  url: http://localhost:9084

#eureka:
#  client:
#    enabled: false
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#  instance:
#    prefer-ip-address: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

logging:
  level:
    org.cts.transactionservice: DEBUG
    org.springframework.security: INFO

